apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "7868319"
    labels:
        datastore_id: "5018755541237760"
data:
    classification: ""
    created: "2020-07-08T20:43:42.196232Z"
    description: "In Terminal.app, on Apple Silicon hardware (I'm using a DTK), run:\r\n\r\n% arch -arch x86_64 git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src.git _gclient_src_mmdd8v1w\r\n\r\nThis will download a bunch of stuff and after about 14 minutes on my system (sooner if your internet is faster) fail like this:\r\n\r\nCloning into '/Users/thakis/src/gn/src/chrome/_gclient_src_mmdd8v1w'...\r\nremote: Sending approximately 21.42 GiB ...        \r\nremote: Counting objects: 307441, done        \r\nremote: Finding sources: 100% (15942/15942)           \r\nerror: inflate: data stream error (incorrect data check)0.43 MiB/s   \r\nfatal: pack has bad object at offset 1433419557: inflate returned -3\r\n\r\n\r\n\r\nThe exact offset is a bit different each time.\r\n\r\nIt works fine when using `arch -arch arm64 ...`.\r\n\r\nWe're seeing this because we ship a python3 binary that's intel only for now, and it launches git as a subprocess, and subprocesses prefer same arch. I'll add an explicit `arch -arch arm64 ...` to the subprocess invocation, so this isn't blocking us, but I figured maybe it's interesting to you â€“ it has easy repro steps and all."
    email: thakis@chromium.org
    modified: "2020-07-08T20:43:42.196397Z"
    number: "7868319"
    number_intvalue: 7868319
    originated: 2020/7/8
    parent_number: '&{NULL_VALUE}'
    product: macos
    product_version: big sur beta 1
    reproducible: always
    resolved: ""
    status: ""
    title: 'x86 git has ''error: inflate: data stream error'' when running under Rosetta 2'
