apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "7925792"
    labels:
        datastore_id: "314401"
data:
    classification: Other bug
    created: "2010-04-30T00:47:36.197154Z"
    description: "30-Apr-2010 02:43 AM Andrea Govoni:\r\nSummary:\r\nI found that most of the times I cannot successfully backup a file on iDisk with Backup 3.2 (v417).\r\nWhen the backup fails, I almost always get this type of error message in ~/Library/Logs/backup.log:\r\n\r\n30/04/10 01:18:16 Backup[198] backup cancelled by user \r\n30/04/10 01:18:16 Backup[198] unable to gzip /tmp/backupTargetTmp.pb39zK/Nuova prova - 2010.04.30-01.18.06.456.backXX/Contents/backup.log: file does not exist \r\n\r\nThe corresponding event log is:\r\n\r\nConnected to MobileMe\r\nBeginning a new Full Backup...\r\nBegin backup at 2010-04-30 01:18:06.456 +0200\r\nScanning files...\r\nAcquired a destination for the backup.\r\nCopied file /Utenti/xfox/Documenti/NoUnicode\r\nThe backup was cancelled by the user.\r\nEnd backup at 2010-04-30 01:18:16.943 +0200\r\n\r\nI get the \"unable to gzip\" error message very often but not always: sometimes the backup succeeds and sometimes I get other error messages. I tried to delete and recreate several backup plans but I didn't manage to find a set of steps that always trigger the issue.\r\nI run Backup on an eMac booted from an external FireWire drive with Mac OS X 10.5.8 (9L31a) Leopard.\r\n\r\n\r\nSteps to Reproduce:\r\n1. Create a simple text file with some garbage text in it and save it to the user's Documents folder.\r\n2. Open Backup and click the + (plus) button to create a new plan.\r\n3. Choose \"Custom\" from the list of templates that appears.\r\n4. Type a name for the plan (for example, \"Test\") and press Return.\r\n5. Click the + (plus) button in the \"Backup Items\" area and choose to include in the plan the text file you created in step 1.\r\n6. Click the + (plus) button in the \"Destination and Schedule\" area and choose iDisk as the destination of the backup.\r\n7. Close the window by clicking the red x circle in the upper left corner of the window.\r\n8. Click \"Back Up\" in the main Backup window.\r\n\r\n\r\nExpected Results:\r\nBackup performs a successfully backup without any errors.\r\n\r\n\r\nActual Results:\r\nSometimes the backup fails and the \"unable to gzip\" error is printed in the backup.log log.\r\n\r\n\r\nRegression:\r\nI've not been able to reproduce this issue on a PowerBook G4 booted from the internal hard drive with the same system version (Mac OS X 10.5.8 Leopard).\r\n\r\n\r\nNotes:\r\nI participated to the AppleSeed Software Customer Seeding program for Backup 3.2, so I updated Backup from all the pre-release builds through the actual version.\r\n\r\n29-May-2015 09:17 PM\r\nI think you may close this report since Backup and iDisk are historyâ€¦\r\n\r\n02-Aug-2016 02:24 PM\r\nDo you keep this open because you are still working on this bug resolution???\r\n\r\nYou\r\nApr 16, 2019 at 7:51 PM\r\nThis issue has been verified by the developer as resolved."
    email: xfox@mac.com
    modified: "2020-01-23T23:05:54.430829Z"
    number: "7925792"
    number_intvalue: 7925792
    originated: 30-Apr-2010 02:43 AM
    parent_number: '&{NULL_VALUE}'
    product: Other
    product_version: Backup 3.2 (v417)
    reproducible: Sometimes
    resolved: No
    status: Closed
    title: Backup 3.2 cannot successfully backup to iDisk
