apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "22350813"
    labels:
        datastore_id: "5458513161617408"
data:
    classification: ""
    created: "2015-08-19T21:50:51.57354Z"
    description: "Summary:\r\nXCTAssert acts as a return statement when it is the last statement in a block returning a BOOL. XCTAssert does not return a value so it should not be a valid result of a non-void function. I suspect this is caused by the XCTAssert{...} macros being implemented as @try/@catch in a compound statement.\r\n\r\nI ran into this bug when I was writing unit tests with the OCMock library. The unit tests was failing in -[OCMArg checkWithBlock:] even thought all the asserts passed because I had forgotten to write \"return YES;\" in one block.\r\n\r\nSteps to Reproduce:\r\nRun the unit tests of the attached project.\r\n\r\nExpected Results:\r\nBlocks ending with XCTAssert{...} should refuse to compile with the error \"Control reaches end of non-void block\".\r\n\r\nActual Results:\r\nThe block compiles without any return statement.\r\n\r\nVersion:\r\nXcode 6.4 w/ iPhone 6 (iOS 8.4) simulator\r\n\r\nNotes:\r\n\r\n\r\nConfiguration:\r\n\r\n\r\nAttachments:\r\n'NoReturn.zip' was successfully uploaded."
    email: green@inkling.com
    modified: "2015-08-19T21:50:51.57378Z"
    number: "22350813"
    number_intvalue: 22350813
    originated: 19-Aug-2015
    parent_number: '&{NULL_VALUE}'
    product: Xcode
    product_version: "6.4"
    reproducible: Always
    resolved: ""
    status: Open
    title: XCTAssert behaves as return statement
