apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "6439685"
    labels:
        datastore_id: "1401"
data:
    classification: Other Bug/Workaround
    created: "2008-12-16T07:40:29.38136Z"
    description: "When I tried to create an AMWorkflow with -[AMWorkflow initWithContentsOfURL:error:],  and passed in a nil NSURL, my program was terminated, and \r\n\"*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSCFDictionary initWithObjects:forKeys:count:]: attempt to insert nil value at objects[0] (key: NSURL)'\"\r\nwas printed to the console.\r\n\r\nI expected the \"error:\" output-parameter to return an NSError explaining any reasons the AMWorklfow couldn't be made.\r\n\r\nSteps to Reproduce:\r\n\r\nid error = nil;\r\nAMWorkflow *workflow = [[AMWorkflow alloc] initWithContentsOfURL:nil error:&error];\r\nNSLog(@\"workflow = %@, error = %@\", workflow, error); //never get here\r\n\r\nResults:\r\nI expected the \"error:\" output-parameter to return an NSError explaining any reasons the AMWorklfow couldn't be made.  If an argument was invalid, I expected the NSError to explain this.  I did not expect an NSInvalidArgumentException to be thrown."
    email: vincent.gable@gmail.com
    modified: "2011-08-28T05:48:52.537242Z"
    number: "6439685"
    number_intvalue: 6439685
    originated: 11-Dec-2008 05:03 PM
    parent_number: '&{NULL_VALUE}'
    product: Automator.framework
    product_version: 10.5.5
    reproducible: Always
    resolved: ""
    status: Open
    title: -[AMWorkflow initWithContentsOfURL:error:] throws an exception when NSURL is nil
