apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "35284626"
    labels:
        datastore_id: "4930543183462400"
data:
    classification: ""
    created: "2017-11-02T18:40:29.14437Z"
    description: "Summary:\r\nWhen requesting products with valid product identifiers on iOS 11 (simulator and device), the request fails with the following error (i.e. the request(_ request: SKRequest, didFailWithError error: Error) delegate method is called):\r\n\r\n(lldb) po error\r\nError Domain=SSErrorDomain Code=0 \"Cannot connect to iTunes Store\" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store}\r\n\r\nThere is an active internet connection (WiFi). This issue seems intermittent, we have noticed it before sporadically.\r\n\r\nThe request is created in the following way:\r\n\r\nlet productIdentifiers = Set([\"ID_1\", \"ID_2\"])\r\nlet request = SKProductsRequest(productIdentifiers: productIdentifiers)\r\nrequest.delegate = self\r\nrequest.start()\r\n\r\nThis happens in both debug builds and release builds.\r\n\r\nIt also sometimes happens when attempting a payment in the `func paymentQueue(_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction])` delegate method the transaction is returned with an error of:\r\n\r\nError Domain=SKErrorDomain Code=0 \"Cannot connect to iTunes Store\" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store}"
    email: kerr.miller@hootsuite.com
    modified: "2017-11-02T18:40:29.14462Z"
    number: "35284626"
    number_intvalue: 35284626
    originated: October 31 2017
    parent_number: '&{NULL_VALUE}'
    product: ""
    product_version: ""
    reproducible: ""
    resolved: ""
    status: Open
    title: SKErrorDomain Code=0 when interfacing with IAP
