apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: FB9794773
    labels:
        datastore_id: "4939320792186880"
data:
    classification: ""
    created: "2021-12-03T23:58:27.0581Z"
    description: "Please describe the issue:\r\nRandomly the tests don't execute and it gives me the error:\r\nExecutable (51237) encountered an error (Test runner never began executing tests after launching. If you believe this error represents a bug, please attach the result bundle at /Users/omarzuniga/Library/Developer/Xcode/DerivedData/Executable-fkblyyjpkdijecbbizlcgirezqxf/Logs/Test/Test-Executable-2021.12.03_16-58-15--0600.xcresult)\r\n\r\nPlease list the steps you took to reproduce the issue:\r\nI run tests locally in Xcode 13.2 by using the repeat function.\r\n\r\nWhat did you expect to happen?\r\nthat all the test executions passed.\r\n\r\nWhat actually happened?\r\nAs you can see in the xcresult file in 2 out of 20 executions it failed with that error.\r\nWhile it was being executed I was able to print a log which later I couldn't find in the xcresult file, I attached it too."
    email: omar.zuniga@rappi.com
    modified: "2021-12-03T23:58:27.058259Z"
    number: FB9794773
    number_intvalue: 9794773
    originated: 12/03/21
    parent_number: '&{NULL_VALUE}'
    product: XCTest
    product_version: Xcode 13.1
    reproducible: Yes
    resolved: ""
    status: Open
    title: Xcode 13.1 - Test runner never began executing tests after launching Recent Similar Reports:None Resolution:Open
