apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "18678800"
    labels:
        datastore_id: "5821119567233024"
data:
    classification: Enhancement
    created: "2014-10-16T16:11:22.218323Z"
    description: "Summary:\r\nSometimes when code executed in a test throws an exception, no future tests will run, and the suite will end with a failure. This seems to specifically happen when the exception is not on the main queue.\r\n\r\nExpected Results:\r\nThe test with the thrown exception fails, and execution of future tests will continue.\r\n\r\nActual Results:\r\nTest execution ends prematurely.\r\n\r\nVersion:\r\nXcode Version 6.0.1 (6A317)\r\n\r\nConfiguration:\r\nRunning the test target of an iOS project in Xcode."
    email: peter.robinett@gmail.com
    modified: "2014-10-23T19:27:17.236408Z"
    number: "18678800"
    number_intvalue: 18678800
    originated: "2014-10-16"
    parent_number: "14436214"
    product: Developer Tools
    product_version: Xcode Version 6.0.1 (6A317)
    reproducible: Sometimes
    resolved: ""
    status: Duplicate/14436214
    title: Exceptions thrown during test execution can take down the entire test runner
